version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    stdin_open: true
    tty: true
    links:
        - db

  db:
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: crimsoncircle

  adminer:
      image: adminer
      restart: always
      ports:
          - 8000:8080
